#!/usr/bin/env python

from json    import load, dump
from smtplib import SMTP
from urllib2 import urlopen

ippy_file = 'ippy2.json';
ippy_conf = load(open(ippy_file));
ippy_echo = load(urlopen(ippy_conf['echo']['uri']))
ippy_myip = ippy_echo[ippy_conf['echo']['key']]

if not ippy_myip == ippy_conf['myip']:
    ippy_conf['myip'] = ippy_myip 
    dump(ippy_conf, open(ippy_file,'wb'), indent=4, sort_keys=True)
    s = SMTP(ippy_conf['smtp']['host'])
    s.login(ippy_conf['smtp']['username'], str(ippy_conf['smtp']['password'])) 
    s.sendmail(
        ippy_conf['smtp']['from'],[ippy_conf['mail']], 
        "From: %1\nSubject: ippy\n\nhi!" % ippy_conf['smtp']['from']
    )         
     
















