#!/usr/bin/env python

from json    import load, dump
from smtplib import SMTP
from urllib2 import urlopen

ippy_file = 'ippy2.json';
ippy_conf = load(open(ippy_file));

print ippy

"""
new_ip = load(urlopen('http://jsonip.com'))['ip']

old_ip = load(open('watchip.json'))['ip']

if not new_ip = old_ip: 
	
	dump({'ip':new_ip}, open('watchip.json','wb'))
"""




message = """From: nightnas <nightnas@nightnas.it>
Subject: SMTP e-mail test

This is a test e-mail message.
"""

"""
s = smtplib.SMTP('m-rb.th.seeweb.it')
s.login('javanile.org16421', 'metal99') 
s.sendmail('nightnas@nightnas.it', ['info.francescobianco@gmail.com'], message)         
print "Successfully sent email"
"""










